# Model Configuration
model:
  in_channels: 3
  model_channels: 128  # Larger model for CIFAR-10
  image_size: 32
  beta_start: 0.0001
  beta_end: 0.02
  num_timesteps: 1000
  # Loss configuration
  loss_type: 'hybrid'
  loss_config:
    weights:
      mse: 0.6
      l1: 0.3
      huber: 0.1
    time_weights:
      type: 'linear'
      max_timesteps: 1000
      beta: 0.1
    reduction: 'mean'

# Training Configuration
training:
  batch_size: 128
  num_epochs: 300  # More epochs for CIFAR-10
  learning_rate: 2e-4
  beta1: 0.9
  beta2: 0.999
  sample_interval: 5
  checkpoint_interval: 10
  num_workers: 4

# Dataset Configuration
dataset:
  name: "cifar10"
  data_dir: "./data"
  image_size: 32

# Logging Configuration
logging:
  use_wandb: true
  wandb_project: "diffusion-models"
  output_dir: "outputs/cifar10"

# Device Configuration
device:
  cuda: true 